export enum StatusMarketListing {
  PENDING = 'PENDING',
  LISTING = 'LISTING',
  LISTING_ERROR = 'LISTING_ERROR',
  LISTED = 'LISTED',
  QUEUE = 'QUEUE',
  DE_LISTED = 'DE_LISTED',
  SOLD = 'SOLD',
  SALE_PENDING = 'SALE_PENDING',
  ERROR_SYNC = 'ERROR_SYNC',
  ERROR = 'ERROR',
  DRAFT = 'DRAFT',
  EXPIRED = 'EXPIRED',
  DELETED = 'DELETED',
  CLOSED_CART_EXPIRED = 'CLOSED_CART_EXPIRED',
  CLOSE = 'CLOSE',
}

export enum MarketType {
  EBAY = 'EBAY',
  POS = 'POS',
  BBB = 'BBB',
  WHOLESALER = 'WHOLESALER',
}

export const SEARCH_TYPE = {
  brand: 'b',
  model: 'm',
  sizeName: 's',
  typeName: 't',
  wheelSize: 'w',
  family: 'fm',
  startPrice: 'ps',
  endPrice: 'pe',
  suspension: 'ss',
  gender: 'g',
  condition: 'c',
  startYear: 'ys',
  endYear: 'ye',
  frameMaterialName: 'f',
  brakeTypeName: 'bt',
  content: 'content',
  isComplete: 'isComplete',
  size: 'page_size',
  sellerType: 'sell_type',
  sort: 'sort',
  location: 'location',
  availableAssembled: 'ins',
  page: 'page',
  pageSize: 'page_size',
  priceRanges: 'priceRanges',
  listingTypes: 'lt',
  storeName: 'sn',
  sortField: 'sortField',
  sortType: 'sortType',
};

export const CannotBuyMarketListingStatuses = [
  StatusMarketListing.SOLD,
  StatusMarketListing.DE_LISTED,
  StatusMarketListing.DELETED,
  StatusMarketListing.EXPIRED,
  StatusMarketListing.SALE_PENDING,
];
