export default {
  NAME: 'Common',
  BASE_URL: '',
  CDN: 'https://s3.amazonaws.com/bbb-v2-dev/',
  CDN_RESOURCE: 'https://d1eye5spyas0l1.cloudfront.net/',
  PATTERN: {
    EMAIL: /^(\s*)[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}(\s*)$/i,
    PHONE: /^(\([0-9]{3}\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$/i,
  },
  SOCIAL: {},
  GA_TRACKING_ID: '',
  GA_MEASUREMENT_ID: 'G-FF04FDT912',
  GG_MAP_API: 'AIzaSyCkgt4YC1oVlvqA77I-9qxm5ckHsr0Yxhg',
  BBB_STAFF: [],
  BBB_RACK: ['5d491a90fff8cc1149427521'],
  PARTNER_CUSTOMER_ID: '5ce527578f473d001f56dcf4',
  WEB_URL: 'https://www.bicyclebluebook.com/',
  WIDGET_URL: 'https://widget-dev.bicyclebluebook.com/',
  STRIPE_API_KEY_B2C: 'pk_test_k5uAq4JphoZKyX1H0QaOtaSz00fTVjCelc',
  STRIPE_API_KEY_P2P: 'pk_test_k5uAq4JphoZKyX1H0QaOtaSz00fTVjCelc',
  SHOW_MODAL_REMOVE_EBIKE: true,
  POS_BASE: 'https://pos-stage.bicyclebluebook.com/',
  X_BBB_CLIENT_SECRET: '',
  RECAPCHA_SITE_KEY: '',
  IMAGE_CDN_URL: '',
  WIDGET_STAGING_URL: 'https://widget-staging.bicyclebluebook.com',
};
